branches:
  - "main"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - prepareCmd: "sed -i 's/\"version\":.*/\"version\": \"${nextRelease.version}\",/g' package.json"
  - "@semantic-release/github"
  - - "@semantic-release/changelog"
    - assets:
        - CHANGELOG.md
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
      message: "chore(release): ${nextRelease.version} \n\n${nextRelease.notes}"